train_steps: 100000
eval_freq: 5000
eval_episodes: 16
checkpoint_freq: 10000
batch_size: 256
debug: false

seeds: 42
n_seeds: 5

wandb_project: pushing_offline_rl
checkpoint_dir: ./checkpoints

#experiment_name 
#pretrain_dir
#pretrain_checkpoint

dataset_path: 'mujoco/hopper/medium-v0'

env_name: "Hopper-v5"
num_envs: 4

train_mode: 
  type: pretrain

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    policy_freq: 2