dataset_path: ""

trainer_config:
  type: refine
  train_steps: 10000
  eval_freq: 100
  eval_episodes: 5
  batch_size: 256
  debug: false
  seed: 42
  wandb_project: pushing_offline_rl
  checkpoint_path: ./checkpoints

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.002
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    scaling_factor_lambda: 5.0

env_name: "MountainCarContinuous-v0"
num_envs: 4