train_steps: 50000
eval_freq: 500
checkpoint_freq: 5000
eval_episodes: 16
batch_size: 256
debug: false
seed: 42
wandb_project: pushing_offline_rl
checkpoint_path: ./checkpoints

train_mode: 
  type: online

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    policy_freq: 2
    alpha_end: 0.2

  warmup_episodes: 16
  expl_noise: 0.1

env_name: "MountainCarContinuous-v0"
num_envs: 4