train_steps: 500000
eval_freq: 10000
checkpoint_freq: 25000
eval_episodes: 32
batch_size: 256
debug: false

seeds: 42
n_seeds: 5

wandb_project: td3-bc

checkpoint_dir: ./checkpoints

experiment_name: 'experiment_10'
pretrain_dir: ./checkpoints/experiment_8/pretrain #<checkpoint_dir>/<experiment_name>/pretrain
#pretrain_checkpoint

dataset_path: 'mujoco/halfcheetah/medium-v0'

env_name: "HalfCheetah-v5"
num_envs: 4

train_mode: 
  type: refine

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    scaling_factor_lambda: 1.0