train_steps: 1000000
eval_freq: 5000
eval_episodes: 10
checkpoint_freq: 25000
batch_size: 256
debug: false

seeds: 42
n_seeds: 5

wandb_project: td3-bc
checkpoint_dir: ./checkpoints

#experiment_name: <optional> 
#pretrain_dir: <pretrain_dir>

env_name: "HalfCheetah-v5"
num_envs: 8

train_mode: 
  type: online

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    policy_freq: 2
    alpha_end: 0.2

  warmup_steps: 25000
  expl_noise: 0.1