train_steps: 1000000
eval_freq: 20000
eval_episodes: 5
checkpoint_freq: 25000
batch_size: 64

seeds: 42
n_seeds: 5

wandb_project: td3-bc
checkpoint_dir: ./checkpoints

#experiment_name: <optional>

dataset_path: dmc/distraction_cheetah_run-alg_ppo-act_2-seg_1-rnd_0/expert-v0

env_name: dmc_distraction_cheetah_run_1-v1
num_envs: 1
env_kwargs:
  action_repeat: 2
frame_stack: 3

train_mode:
  type: pretrain_ftd

  td3_config:
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    alpha: 0.4
    actor_lr: 3e-4
    critic_lr: 3e-4
    policy_freq: 2

    policy_config:
      type: cnn_ftd
      
      cnn_encoder_cfg:
        cnn_filter_dims: [32, 64, 128, 256]
        cnn_kernel_strides: [2, 2, 1, 1]

        attn_selector_cfg:
          conv_layers: 5
          conv_filters: 32
          attention_embed_dim: 128
          attention_heads: 4

      actor_cfg:
        linear_trunk_dim: 64
        hidden_dim: 256
        n_layers: 2

      critic_cfg:
        linear_trunk_dim: 64
        hidden_dim: 256
        n_layers: 2

    predictor_hidden_dim: 1024
    reward_factor: 1.0
    inverse_factor: 1.0
    max_grad_norm: 5.0
    predictors_lr: 1e-4

    predictors_update_freq: 0 # currently turned off
    predictors_update_slow_freq: 50_000
    predictors_warmup_steps: 10_000

    log_img_freq: 500