import flax.nnx as nn
from stable_baselines3.common.utils import get_linear_fn

HYPERPARAMETERS = {
    "dmc_cheetah_run_1-v1": {
        "normalize": True,
        "n_envs": 1,
        "policy": "MlpPolicy",
        "n_timesteps": 1_000_000,
        "batch_size": 64,
        "n_steps": 512,
        "gamma": 0.98,
        "learning_rate": 2.0633e-05,
        "ent_coef": 0.000401762,
        "clip_range": 0.1,
        "n_epochs": 20,
        "gae_lambda": 0.92,
        "max_grad_norm": 0.8,
        "vf_coef": 0.58096,
        "policy_kwargs": {
            "log_std_init": -2,
            "ortho_init": False,
            "activation_fn": nn.relu,
            "net_arch": {"pi": [256, 256], "vf": [256, 256]},
        },
        "normalize_kwargs": {"norm_obs": True, "norm_reward": True},
        "env_kwargs": {"action_repeat": 4},
    },
    "dmc_hopper_run_1-v1": {
        "normalize": True,
        "n_envs": 1,
        "policy": "MlpPolicy",
        "n_timesteps": 1_000_000,
        "batch_size": 32,
        "n_steps": 512,
        "gamma": 0.999,
        "learning_rate": 9.80828e-05,
        "ent_coef": 0.00229519,
        "clip_range": 0.2,
        "n_epochs": 5,
        "gae_lambda": 0.99,
        "max_grad_norm": 0.7,
        "vf_coef": 0.835671,
        "policy_kwargs": {
            "log_std_init": -2,
            "ortho_init": False,
            "activation_fn": nn.relu,
            "net_arch": {"pi": [256, 256], "vf": [256, 256]},
        },
    },
    "dmc_humanoid_run_1-v1": {
        "normalize": True,
        "n_envs": 1,
        "policy": "MlpPolicy",
        "n_timesteps": 10_000_000,
        "batch_size": 256,
        "n_steps": 512,
        "gamma": 0.95,
        "learning_rate": 3.56987e-05,
        "ent_coef": 0.00238306,
        "clip_range": 0.3,
        "n_epochs": 5,
        "gae_lambda": 0.9,
        "max_grad_norm": 2,
        "vf_coef": 0.431892,
        "policy_kwargs": {
            "log_std_init": -2,
            "ortho_init": False,
            "activation_fn": nn.relu,
            "net_arch": {"pi": [256, 256], "vf": [256, 256]},
        },
    },
    "dmc_reacher_easy_1-v1": dict(
        n_envs = 16,
        normalize = True,
        normalize_kwargs = dict(norm_obs=True, norm_reward=True, clip_obs=10.0, clip_reward=10.0),
        n_steps = 1024,            # per env → 16*256 = 4096 rollout batch
        batch_size = 2048,
        n_epochs = 10,
        learning_rate = get_linear_fn(start=1e-4, end=3e-5, end_fraction=1.0),
        gamma = 0.99,
        gae_lambda = 0.95,
        clip_range = 0.2,
        vf_coef = 0.5,
        ent_coef = 0.0,           # optional: 1e-3 if exploration is too timid
        max_grad_norm = 0.5,
        use_sde = True,           # helps on small state tasks
        sde_sample_freq = 4,
        policy = "MlpPolicy",
        policy_kwargs = dict(net_arch=dict(pi=[64,64], vf=[64,64]), ortho_init=True),
        n_timesteps = 1_000_000,
        gamma_eval = 0.99,
        env_kwargs = dict(action_repeat=1),
    )
}